version: "3.8"

services:
  db:
    container_name: db
    image: postgis/postgis:12-master
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - webnet
    expose:
      - 5432
    env_file: ./config/.env
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'dev_db'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web: &web
    container_name: web
    env_file: ./config/.env
    build:
      target: development_build
      args:
        DJANGO_ENV: 'dev'
    volumes:
      - ./backend:/code
      - ./config:/config
    environment:
      DJANGO_DEBUG: 1
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/dev_db'
      DATABASE_HOST: 'db'
    depends_on:
      - db
    command: sh /runserver.sh

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    command: [ "-smtp-bind-addr", "0.0.0.0:25" ]
    user: root
    restart: on-failure
    networks:
      - webnet
      - nginx_network
    expose:
      - 25
      - 8025
    healthcheck:
      test: [ "CMD", "echo", "|", "telnet", "127.0.0.1 25" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    build:
      target: development_build
    ports:
      - 8025:8025
    depends_on:
      - mailhog

volumes:
  db-data: